version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: smartform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      JPA_HIBERNATE_DDL_AUTO: create-drop
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/smartform
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres